version: '3.8'

services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=mittstyremote
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - DIARIZE_URL=http://diarization:8000/diarize
    depends_on:
      - db
      - redis
      - diarization
    networks:
      - app-network

  # MySQL database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mittstyremote
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Redis for queue and cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Python diarization service
  diarization:
    build:
      context: ./python-diarization
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ./python-diarization:/app
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
